---
- hosts: node
  tasks:
   - name: Creating a user
     user:
        name: chetan
        state: present
   - name: Create a file
     file:
       path: /home/ubuntu/testing 
       state: touch
